### ISSUE TITLE
Encounter an issue to login to Airflow

### ISSUE THREAD

**Issue by phoenixml** [TJaniF/airflow-kafka-quickstart#2]
Hi there, 
Thank you for this project, I was searching for a proper airflow integration with Kafka (Airflow have a native kafka connector) and I came across this project and I hope kafka is supported as integration ;)
 
However, I used the second method Option2 from Astro CLI to bring the infra up all went well after executing the command "astro dev start" , until I reached into a prompt login interface on my terminal (CLI) asking to sign in, I tried the default creds:
username: airflow
password: airflow

However, I am not able to sign in, also I am not able to access airflow from the browser (maybe separate issue). I am assuming I should first sign in successfully from the CLI then will be able to login from the browser ? If so then what are the creds used in this project. I couldn't find any in a .env file or defined somewhere maybe I missed something. 

Thank you for your help :)

**Comment by TJaniF** [comment]
@phoenixml Thank you for your message!
And good callout, I should put the default creds into the readme! What should happen is that after you run `astro dev start` you should have a local Airflow instance running with the webserver UI at `localhost:8080` where you can sign in with username: `admin`, password: `admin` (this is the default for the Astro CLI). Hope this helps! :)

**Comment by phoenixml** [comment]
Hi Tamara,

Thank you for the updates, sure how I missed the default admin admin 😉 
Thank you I will close this issue.
Cheers.

**Comment by phoenixml** [comment]
Hi @TJaniF (Tamara),

Sorry to bother you again, I didn't mentioned earlier that I setup this project on AWS and not on local, I am able to access airflow from another project I was exploring before, where I exposed and routed all the requirements to access the web interface from a public IP successfully, but when it comes to this project I only can see the cli interface allows me to login to airflow but unfortunately not able to do so from external IP like i did before with other airflow containers. I am wondering if we need to expose other ports? but on the documentation u said port 8080 which is what I used before. Any ideas what could be the issue, I saw that on this project it is using streamlit app and other kind of apps, could be this is related?

Thank you heaps, I see that this project help me in including all Kafka requirements to communicate with airflow if it works properly on my end and I enjoyed using astro for the first time a good way to manage the containers, which I am excited to make this project work on my end.
Cheers

**Comment by TJaniF** [comment]
@phoenixml 

Oh that is a good question! I assume you are running on Amazon ECS? I have not done that before personally so I am not sure how the interconnectivity there would work. 
This project runs everything locally and connects it via a network (aptly named `my_network`). The local Kafka container uses port 9092 and 19092 (Airflow connects via kafka:19092). The zookeeper uses port 2181. (the Airflow components use default ports, 8080 for the webserver, 5432 for the postgres metastore). 

I am no sure where you found streamlit in this haha, I did use streamlit for my [other Airflow quickstart](https://github.com/TJaniF/airflow-elt-blueprint) though.

You can see the setup in the docker-compose.override: https://github.com/TJaniF/airflow-kafka-quickstart/blob/main/docker-compose.override.yml .

This took me a _while_ to stitch together, got help from both a more infra-experienced engineer and this blogpost: https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/ (scenario 5 was my use case)

I unfortunately don't have the setup ready to test how that would connect on ECS, but I will ask around for ideas. :)

**Comment by phoenixml** [comment]
Thank you so much for your response and the links you shared I will take a look. Hahaha you are correct the streamlit was from the other repo. I am running the project on local and all working fine appreciated @TJaniF :)
